from __future__ import annotations
from typing import Optional, List
from datetime import datetime
from pydantic import BaseModel, Field, field_validator
import uuid


class TaskSpec(BaseModel):
    """Parsed and validated founder request."""
    task_id: str = ""
    agent_name: str
    agent_role: str
    agent_mission: str
    allowed_tools: List[str]
    token_budget: int = 10000
    department: str = "general"
    founder_request: str

    @field_validator("task_id", mode="before")
    @classmethod
    def set_task_id(cls, v: str) -> str:
        """Auto-generate task_id if not provided."""
        return v or str(uuid.uuid4())

    @field_validator("agent_name")
    @classmethod
    def validate_agent_name(cls, v: str) -> str:
        """Ensure agent name is lowercase with underscores only."""
        if not v.replace("_", "").replace("-", "").isalnum():
            raise ValueError("agent_name must contain only letters, numbers, underscores, hyphens")
        return v.lower().replace("-", "_")

    @field_validator("token_budget")
    @classmethod
    def validate_token_budget(cls, v: int) -> int:
        """Ensure token budget does not exceed system maximum."""
        if v > 10000:
            raise ValueError("token_budget cannot exceed 10000")
        return v


class AgentSpec(BaseModel):
    """Complete 16-component Agent DNA Schema generated by Meta-Agent."""
    agent_name: str
    version: str = "1.0"
    department: str = "general"
    mission: str
    domain_knowledge: List[str] = []
    competencies: List[str] = []
    technical_skills: List[str] = []
    experience_patterns: List[str] = []
    reasoning_framework: List[str] = []
    decision_rules: List[str] = []
    execution_workflow: List[str] = []
    allowed_tools: List[str] = []
    memory_interface: dict = {}
    communication_protocol: dict = {}
    quality_standards: List[str] = []
    responsibilities: List[str] = []
    non_responsibilities: List[str] = []
    verification_logic: List[str] = []
    observability: dict = {}
    escalation_triggers: List[str] = []
    token_budget: int = 10000
    default_model: str = ""
    fallback_model: str = "gpt-5"
    memory_policy: str = "session_only"
    retry_policy: dict = {"max_attempts": 3, "backoff_seconds": 2}

    @field_validator("default_model", mode="before")
    @classmethod
    def set_default_model(cls, v: str) -> str:
        """Read model from environment if not set."""
        import os
        return v or os.getenv("PRIMARY_MODEL", "claude-sonnet-4-6")


class VerificationResult(BaseModel):
    """Result from GPT-4o spec verification."""
    status: str
    issues: List[str] = []
    suggestions: List[str] = []
    verified_by: str = "gpt-4o"

    @field_validator("status")
    @classmethod
    def validate_status(cls, v: str) -> str:
        """Status must be one of three values."""
        allowed = {"PASS", "CONDITIONAL", "FAIL"}
        if v.upper() not in allowed:
            raise ValueError(f"status must be one of {allowed}")
        return v.upper()


class TestResult(BaseModel):
    """Result from pytest execution on generated agent."""
    passed: int = 0
    failed: int = 0
    errors: int = 0
    total: int = 0
    success: bool = False
    output: str = ""


class AuditEntry(BaseModel):
    """Single audit log entry written after every action."""
    agent_id: str
    task_id: str
    action: str
    details: dict = {}
    tokens_used: int = 0
    success: bool = True
    logged_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())

    @field_validator("logged_at", mode="before")
    @classmethod
    def set_logged_at(cls, v: str) -> str:
        """Auto-set timestamp if not provided."""
        return v or datetime.utcnow().isoformat()


class FounderReport(BaseModel):
    """Final report returned to founder after every task."""
    task_id: str
    agent_name: str
    status: str
    summary: str
    agent_spec: Optional[AgentSpec] = None
    verification_result: Optional[VerificationResult] = None
    test_result: Optional[TestResult] = None
    registry_id: Optional[str] = None
    total_tokens_used: int = 0
    errors: List[str] = []
    rollback_command: str = ""
    completed_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())

    @field_validator("completed_at", mode="before")
    @classmethod
    def set_completed_at(cls, v: str) -> str:
        """Auto-set timestamp if not provided."""
        return v or datetime.utcnow().isoformat()


class MetaAgentState(BaseModel):
    """LangGraph state object passed between all 9 nodes."""
    task_id: str = ""
    session_id: str = ""
    founder_request: str = ""
    task_spec: Optional[TaskSpec] = None
    agent_spec: Optional[AgentSpec] = None
    verification_result: Optional[VerificationResult] = None
    generated_code: Optional[str] = None
    generated_yaml: Optional[str] = None
    test_result: Optional[TestResult] = None
    registration_result: Optional[dict] = None
    total_tokens_used: int = 0
    errors: List[str] = []
    should_stop: bool = False
    founder_report: Optional[FounderReport] = None

    @field_validator("task_id", mode="before")
    @classmethod
    def set_task_id(cls, v: str) -> str:
        """Auto-generate task_id if not provided."""
        return v or str(uuid.uuid4())

    @field_validator("session_id", mode="before")
    @classmethod
    def set_session_id(cls, v: str) -> str:
        """Auto-generate session_id if not provided."""
        return v or str(uuid.uuid4())


async def init_db() -> None:
    """应用启动时初始化可选本地数据库结构（失败则忽略）。"""
    try:
        from agents.meta_agent.sqlite_app_db import init_sqlite_schema

        init_sqlite_schema()
    except Exception:
        pass
