with open("agents/meta_agent/models.py", "r", encoding="utf-8") as f:
    content = f.read()

old = '''class AgentSpec(BaseModel):
    """Complete agent specification generated by Meta-Agent."""
    agent_name: str
    version: str = "1.0"
    mission: str
    responsibilities: List[str]
    non_responsibilities: List[str]
    allowed_tools: List[str]
    token_budget: int = 10000
    default_model: str = ""
    fallback_model: str = "gpt-4o"
    retry_policy: dict = {"max_attempts": 3, "backoff_seconds": 2}
    escalation_triggers: List[str] = []
    memory_policy: str = "session_only"
    department: str = "general"'''

new = '''class AgentSpec(BaseModel):
    """Complete 16-component Agent DNA Schema generated by Meta-Agent."""
    agent_name: str
    version: str = "1.0"
    department: str = "general"
    mission: str
    domain_knowledge: List[str] = []
    competencies: List[str] = []
    technical_skills: List[str] = []
    experience_patterns: List[str] = []
    reasoning_framework: List[str] = []
    decision_rules: List[str] = []
    execution_workflow: List[str] = []
    allowed_tools: List[str] = []
    memory_interface: dict = {}
    communication_protocol: dict = {}
    quality_standards: List[str] = []
    responsibilities: List[str] = []
    non_responsibilities: List[str] = []
    verification_logic: List[str] = []
    observability: dict = {}
    escalation_triggers: List[str] = []
    token_budget: int = 10000
    default_model: str = ""
    fallback_model: str = "gpt-5"
    memory_policy: str = "session_only"
    retry_policy: dict = {"max_attempts": 3, "backoff_seconds": 2}'''

content = content.replace(old, new)
with open("agents/meta_agent/models.py", "w", encoding="utf-8") as f:
    f.write(content)
print("AgentSpec updated with 16-component DNA schema")
